project:
  type: website

website:
  title: "stats<span class='fancy-four'>4</span>datascience"
  favicon: assets/favicon.png
  navbar:
    logo: assets/favicon.png
    left:
      - text: Software
        menu: 
          - text: stats4phc R package
            href: https://github.com/Genentech/stats4phc
    right:
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    css: assets/styles.css
    cls: assets/vancouver-brackets.cls
    toc: true
    fig-align: center
