project:
  type: website

website:
  title: "stats<span class='fancy-four'>4</span>datascience"
  favicon: assets/favicon.png
  navbar:
    background: primary
    logo: assets/favicon.png
    right:
      - text: Software
        href: software.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    css: assets/styles.css
    cls: assets/vancouver-brackets.cls
    toc: true
    fig-align: center

resources:
  - "assets/additive_model_slide.pdf"
